# CMake generated Testfile for 
# Source directory: C:/Users/chris/OneDrive/Documents/GitHub/video-game
# Build directory: C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[world_clock_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Debug/world_clock_tests.exe")
  set_tests_properties([=[world_clock_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;17;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[world_clock_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Release/world_clock_tests.exe")
  set_tests_properties([=[world_clock_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;17;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[world_clock_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/MinSizeRel/world_clock_tests.exe")
  set_tests_properties([=[world_clock_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;17;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[world_clock_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/RelWithDebInfo/world_clock_tests.exe")
  set_tests_properties([=[world_clock_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;17;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
else()
  add_test([=[world_clock_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[engine_config_loader_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Debug/engine_config_loader_tests.exe")
  set_tests_properties([=[engine_config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;21;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[engine_config_loader_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Release/engine_config_loader_tests.exe")
  set_tests_properties([=[engine_config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;21;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[engine_config_loader_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/MinSizeRel/engine_config_loader_tests.exe")
  set_tests_properties([=[engine_config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;21;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[engine_config_loader_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/RelWithDebInfo/engine_config_loader_tests.exe")
  set_tests_properties([=[engine_config_loader_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;21;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
else()
  add_test([=[engine_config_loader_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[subsystem_pipeline_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Debug/subsystem_pipeline_tests.exe")
  set_tests_properties([=[subsystem_pipeline_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;25;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[subsystem_pipeline_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Release/subsystem_pipeline_tests.exe")
  set_tests_properties([=[subsystem_pipeline_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;25;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[subsystem_pipeline_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/MinSizeRel/subsystem_pipeline_tests.exe")
  set_tests_properties([=[subsystem_pipeline_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;25;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[subsystem_pipeline_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/RelWithDebInfo/subsystem_pipeline_tests.exe")
  set_tests_properties([=[subsystem_pipeline_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;25;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
else()
  add_test([=[subsystem_pipeline_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[world_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Debug/world_tests.exe")
  set_tests_properties([=[world_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;29;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[world_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Release/world_tests.exe")
  set_tests_properties([=[world_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;29;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[world_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/MinSizeRel/world_tests.exe")
  set_tests_properties([=[world_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;29;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[world_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/RelWithDebInfo/world_tests.exe")
  set_tests_properties([=[world_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;29;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
else()
  add_test([=[world_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[playtest_simulation_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Debug/playtest_simulation_tests.exe")
  set_tests_properties([=[playtest_simulation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;66;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[playtest_simulation_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/Release/playtest_simulation_tests.exe")
  set_tests_properties([=[playtest_simulation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;66;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[playtest_simulation_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/MinSizeRel/playtest_simulation_tests.exe")
  set_tests_properties([=[playtest_simulation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;66;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[playtest_simulation_tests]=] "C:/Users/chris/OneDrive/Documents/GitHub/video-game/build-vs2022/RelWithDebInfo/playtest_simulation_tests.exe")
  set_tests_properties([=[playtest_simulation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;66;add_test;C:/Users/chris/OneDrive/Documents/GitHub/video-game/CMakeLists.txt;0;")
else()
  add_test([=[playtest_simulation_tests]=] NOT_AVAILABLE)
endif()
